"""from typing import Optional
import logging
import os
import random
import requests
from tenacity import retry, stop_after_attempt, wait_exponential_jitter, retry_if_exception_type
from config import settings

logger = logging.getLogger("guidefarm.llm")

class LLMService:
    """LLM service abstraction. Supports providers: openai|mistral|local fallback.

    Uses tenacity for robust retry/backoff. Mistral key must be provided via
    environment (settings.MISTRAL_API_KEY) or CI/Secrets. No keys are stored in code.
    """
    def __init__(self):
        self.provider = settings.LLM_PROVIDER or "mistral"
        self.mistral_key = settings.MISTRAL_API_KEY
        self.mistral_model = os.environ.get("MISTRAL_MODEL", "mistral-medium-latest")
        default_url = f"https://api.mistral.ai/v1/models/{self.mistral_model}/completions"
        self.mistral_url = os.environ.get("MISTRAL_API_URL", default_url)

    def generate_markdown(self, topic: str, lang: str = "ru", provider: Optional[str] = None) -> str:
        provider = provider or self.provider
        logger.info({"event": "llm_call", "provider": provider, "topic": topic})
        if provider == "mistral" and self.mistral_key:
            try:
                return self._call_mistral(topic, lang)
            except Exception:
                logger.exception("Mistral call failed, falling back to local generator")
        return self._local_markdown(topic)

    @retry(reraise=True, stop=stop_after_attempt(4), wait=wait_exponential_jitter(initial=1, max=10),
           retry=retry_if_exception_type(Exception))
    def _call_mistral(self, topic: str, lang: str = "ru") -> str:
        prompt = self._build_prompt(topic, lang)
        headers = {
            "Authorization": f"Bearer {self.mistral_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "input": prompt,
            "max_tokens": 2000,
            "temperature": 0.7,
        }
        resp = requests.post(self.mistral_url, headers=headers, json=payload, timeout=30)
        if resp.status_code != 200:
            logger.warning({"event": "mistral_non_200", "status": resp.status_code, "body": resp.text[:400]})
            resp.raise_for_status()
        try:
            data = resp.json()
        except Exception:
            logger.exception("Failed to decode JSON from mistral response")
            raise
        text = self._extract_text_from_mistral_response(data)
        if text:
            return text
        logger.warning({"event": "mistral_no_text", "data": data})
        raise RuntimeError("Mistral returned no usable text")

    def _extract_text_from_mistral_response(self, data: dict) -> Optional[str]:
        candidates = []
        if not isinstance(data, dict):
            return None
        if "outputs" in data and isinstance(data["outputs"], list):
            for o in data["outputs"]:
                if isinstance(o, dict):
                    for k in ("content", "text", "output", "message"):
                        v = o.get(k)
                        if isinstance(v, str) and v:
                            candidates.append(v)
                elif isinstance(o, str):
                    candidates.append(o)
        if "output" in data and isinstance(data["output"], str):
            candidates.append(data["output"])
        if "choices" in data and isinstance(data["choices"], list):
            for c in data["choices"]:
                if isinstance(c, dict):
                    t = c.get("text")
                    if isinstance(t, str) and t:
                        candidates.append(t)
                    m = c.get("message")
                    if isinstance(m, dict):
                        cont = m.get("content")
                        if isinstance(cont, str) and cont:
                            candidates.append(cont)
        for key in ("text", "content", "result", "message"):
            v = data.get(key)
            if isinstance(v, str) and v:
                candidates.append(v)
        if not candidates:
            return None
        candidates = [c.strip() for c in candidates if c and isinstance(c, str)]
        candidates.sort(key=lambda s: len(s), reverse=True)
        return candidates[0]

    def _build_prompt(self, topic: str, lang: str) -> str:
        return f"Сгенерируй подробный guide по теме: {topic} в markdown (титул, оглавление, 5 глав, чек-листы)."

    def _local_markdown(self, topic: str) -> str:
        logger.info({"event": "llm_local_fallback", "topic": topic})
        md = f"# {topic}\n\n_Premium #DOBRO guide generated locally_\n\n## Оглавление\n\n1. Введение\n2. План\n3. Шаги\n4. Примеры\n5. Чек-лист\n\n## Введение\n\nТема: {topic}\n\n## План\n\n- Шаг 1\n- Шаг 2\n\n## Чек-лист\n\n- [ ] Протестировать\n- [ ] Опубликовать\n\n---\n\n*Generated by GuideFarm (local fallback).*"
        return md
"""